apiVersion: guize.io/v1
kind: DeploymentProfile
metadata:
  name: edge-media-a380
  version: 1.0.0
spec:
  runtime: docker-compose
  requirements:
    architecture: amd64
  services:
    - guize-worker-agent
    - guize-media-service
  optionalServices: []
  security:
    signatureRequired: true
